wandb_version: 1

__wrapped__:
  desc: null
  value: wandb.sdk.wandb_config.Config
_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1630223630
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 1
      4: 3.8.5
      5: 0.12.1
      8:
      - 6
aug_num:
  desc: null
  value: 4
augmentation:
  desc: null
  value: false
batch_size:
  desc: null
  value: 32
device:
  desc: null
  value: cuda
early_stopping:
  desc: null
  value: 3
epoches:
  desc: null
  value: 100
k_fold_num:
  desc: null
  value: -1
load_augmentation:
  desc: null
  value: false
loss:
  desc: null
  value: Crossentropy_foscal
loss1_weight:
  desc: null
  value: 0.1
loss2_weight:
  desc: null
  value: 0.9
lr:
  desc: null
  value: 0.001
model_name:
  desc: null
  value: mobilenetv2_100
optimizer:
  desc: null
  value: AdamW
scheduler:
  desc: null
  value: CosineAnnealingLR
train_csv_path:
  desc: null
  value: ../../input/data/train/train.csv
train_images_path:
  desc: null
  value: ../../input/data/train/images/
